### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by niroop893** [shreyasingh824/CrackWPAPassword#1]
┌──(kali㉿kali)-[~/CrackWPAPassword]
└─$ python wifihacking.py
Traceback (most recent call last):
File "/home/kali/CrackWPAPassword/wifihacking.py", line 18, in
pcap[0][4].raw_mode=True
~~~~~~~^^^
File "/home/kali/.local/lib/python3.11/site-packages/pyshark/packet/packet.py", line 48, in getitem
return self.layers[item]
~~~~~~~~~~~^^^^^^
IndexError: list index out of range

**Comment by shreyasingh824** [comment]
send me the screenshot of your code as well as error.

**Comment by niroop893** [comment]
[test.docx](https://github.com/shreyasingh824/CrackWPAPassword/files/13596732/test.docx)
pls find the screen shot
